### ISSUE TITLE
La traduction semi-automatique est-elle acceptée ?

### ISSUE THREAD

**Issue by jibe-b** [JulienLecaille/P2PAccounting#1]
Bonjour @JulienLecaille, faire travailler [deepl.com](deepl.com) puis affiner manuellement le résultat en veillant à ce qu'il soit fidèle à la version d'origine, est-ce que ça te convient ?

**Comment by JulienLecaille** [comment]
Ca me va très bien, c'est comme cela que j'envisageais de faire !

**Comment by jibe-b** [comment]
Magnifique ! C'est ce qu'on avait commencé avec HackYourPhD pour la traduction du book.fosteropenscience.eu mais on l'a mis en pause pour s'associer avec un autre collectif qui veut faire cette traduction. https://github.com/jibe-b/Open-Science-TrainingHandbook_FR

**Comment by jibe-b** [comment]
@JulienLecaille J'arrive pour t'aider dès que je trouve un moment ! Et si ce n'est pas sur ce texte, ça sera sur un sur les communs/p2p/etc
